---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        run: hello
    spec:
      containers:
      - image: jeffreyvdb/hello:1.1.0
        name: hello
        resources: {}
