apiVersion: v1
kind: Service
metadata:
  namespace: hello-app
  labels:
    app: hello
    project: hello
  name: hello
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
  type: ClusterIP
